CREATE TABLE IF NOT EXISTS `tb_ai_review_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `activity_id` bigint unsigned NOT NULL,
  `task_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `suggestion` varchar(32) NOT NULL DEFAULT 'UNKNOWN',
  `risk_level` varchar(32) NOT NULL DEFAULT 'UNKNOWN',
  `score` int DEFAULT NULL,
  `problems_json` text,
  `missing_fields_json` text,
  `similar_activities_json` text,
  `similarity_analysis` varchar(1024) DEFAULT NULL,
  `review_comment` varchar(2048) DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `prompt_version` varchar(64) NOT NULL DEFAULT 'v1',
  `raw_response` text,
  `parse_status` varchar(32) NOT NULL DEFAULT 'PARSED',
  `error_message` varchar(1024) DEFAULT NULL,
  `manual_review_result` varchar(32) DEFAULT NULL,
  `manual_review_remark` varchar(512) DEFAULT NULL,
  `manual_reviewed_at` datetime DEFAULT NULL,
  `is_ai_adopted` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_review_activity_prompt` (`activity_id`,`prompt_version`),
  KEY `idx_ai_review_status` (`task_status`,`updated_at`),
  KEY `idx_ai_review_activity` (`activity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动 AI 辅助审核记录表';
